### ISSUE TITLE
gcc 4.8 vs 4.9 vs clang

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen-cache#10]
Consultation/hint/tips on this stumper pls ...

There is a test fail after this fix that has me stumped. https://travis-ci.org/mapbox/carmen-cache/builds/46816335. This change attempts to preserve the order of spatialMatch results when equal relevs are compared -- either the order of the results going into the sort is different or the sort itself is behaving differently:

- Fails run on linux / gcc 4.8 https://travis-ci.org/mapbox/carmen-cache/builds/46816335
- Passes run on linux / gcc 4.9 https://travis-ci.org/mapbox/carmen-cache/jobs/46817462
- Fails on OS X / both gcc+clang https://travis-ci.org/mapbox/carmen-cache/jobs/46819631

Tips on where/how to debug here?

**Comment by DennisOSRM** [comment]
Different compiler (versions) implement sorting differently. If your comparison function isn't a strict weak ordering this can lead to issues. Do you have a link to the change in question?

**Comment by yhahn** [comment]
@DennisOSRM yes, here is the change:

https://github.com/mapbox/carmen-cache/commit/34a17c12a55462d09a80747f97e382b898ad61d8#diff-672b939c4bdf28c42fc7ba5da56105dbR1386

**Comment by yhahn** [comment]
Punting on this issue by rolling back ^^. Other smarter ways to address this.

**Comment by DennisOSRM** [comment]
Stable sort didn't help?

**Comment by yhahn** [comment]
No, my hunch was that stable sort was functioning correctly but the input was ordered differently between the gcc48 vs gcc49 cases. After some thought functionally relying on the sort order of this input seems like a bad idea overall so I ditched the change above.
