### ISSUE TITLE
[setgrid] Add unit tests for _set() with grid objects

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen-cache#100]
For this task you'll be getting familiar with

- Requiring modules in node and calling methods from them
- Unit testing in node using its native [assert methods](https://nodejs.org/api/assert.html)
- Defining tests using the [tape module](https://github.com/substack/tape)

------

- [x] Create a new test file for your tests at `test/cache-setgrid.test.js`
- [x] Start by adding the example API usage from the main quest ticket (https://github.com/mapbox/carmen-cache/issues/99) to your file:

    ```js
    var carmenCache = require('carmen-cache');
    var grids = new carmenCache.MemoryCache('grids');

    var a = 7036891598684201;
    var b = 4785263596273714;
    var c = 7036994682093628;

    // store the data in the cache
    grids._set('paris', [a,b,c]);
    ```

    Because your test file is actually within the `carmen-cache` module, you'll need to reference it in your require using a relative path like this:

    ```js
    var carmenCache = require('../index.js');
    ```

    Run your test file using `node test/cache-setgrid.test.js` to make sure there are no syntax errors.

- [x] Sketch out basic unit tests for the existing API:

    - You should be able to call `_set()` using `paris` as the cache key and with a list of numbers
    - You should be able to call `_get()` using `paris` as the cache key and get a list of numbers back

    To do this, you can make use of the tape API for defining tests:

    ```js
    var tape = require('tape');

    tape('basic API', function(assert) {
        // code and assertions run here
        var foo = 5 + 7;
        assert.equal(foo, 12, 'addition works!');

        // when your test is done you must call assert.end() explicitly
        assert.end();
    });
    ```

- [x] Sketch out the test flow you'd like for respresenting the new API:

    - You should be able to call `_set()` using `paris` as the cache key and with a list of grid objects
    - You should be able to call `_get()` using `paris` as the cache key and get a list of numbers back
    - You should be able to verify that the numbers returned are the grid objects converted to single numbers properly

    For verifying that the conversion occurred correctly, you can make use of the `test/grid.js` library which provides utility encode/decode functions for converting between grid properties and their numeric equivalents.

- [x] Make a Pull Request against the `setgrid` branch with your work!

**Comment by fredngeorge** [comment]
PR merged.
