### ISSUE TITLE
[setgrid] Add an encodeGrid() cpp method

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen-cache#101]
For this task you'll be getting familiar with

- Defining JS API methods in C++
- Converting JS values into C++ types and vice versa
- Creating C++ functions in the `binding.cpp` file

------

- [x] Ping @apendleton or @yhahn for a walkthrough of
  - Defining a new JS method in C++
  - Grabbing an argument from JS in C++
  - Converting it to a C++ type
  - Rebuilding your C++ code and testing it from JS
- [x] Create an `encodeGrid()` cpp function
  - The function will take the following arguments:
    - relev
    - score
    - x
    - y
    - id
  - The function will return a `uint64_t`
  - You may want to use types consistent with the `Cover` struct (https://github.com/mapbox/carmen-cache/blob/master/src/binding.cpp#L1077-L1089)
  - The function should serve the same function as the `grid.encode()` method in JavaScript (https://github.com/mapbox/carmen-cache/blob/master/test/grid.js#L16-L27)
- [x] Expose your `encodeGrid()` cpp function to JS as a MemoryCache method
- [x] Add JS unit tests that confirm `cache.encodeGrid()` behaves the same `grid.encode()`
- [x] Make a Pull Request against the setgrid branch with your work!

**Comment by fredngeorge** [comment]
Branch merged.
