### ISSUE TITLE
[setgrid] Wire up encodeGrid() and _set()

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen-cache#103]
![server rack](https://blog.dotcom-monitor.com/wp-content/uploads/2010/08/grayedmess.jpg)

Now that the pieces are in place let's look into wiring it all up:

- [x] Read through the current `_set()` function
- [x] Before making changes in the code, sketch out some notes on how you want to approach this
  - How and where in the code will you optionally handle the grid objects coming in from JavaScript?
  - How will you convert that data into covers?
  - @apendleton or @yhahn can give you a good gutcheck on approach
- [x] Apply those changes and work through any issues as you toward getting the original setgrid unit tests to pass
- [x] Make a Pull Request against the setgrid branch with your work!

cc @fredngeorge

**Comment by fredngeorge** [comment]
Branch merged.
