### ISSUE TITLE
[setgrid] Building dev binaries

### ISSUE THREAD

**Issue by yhahn** [mapbox/carmen-cache#106]
**Goal:** we're going to switch gears and start using your work as a dependency in a branch of carmen so you can start testing out your new API.

- You'll get familiar with semver and creating dev versions of a project
- You'll learn how to trigger a binary build of a project
- You'll learn how to point at dev dependency of another module from a `package.json` file

------

- [x] Create a branch off of `setgrid`
- [x] Check out the [semver docs](http://semver.org/) and how npm handles [semver versioning for especially for prerelease builds](https://docs.npmjs.com/misc/semver#prerelease-tags)
- [x] In your new branch, edit `package.json` and update the `version` property to be for a prerelease of the next version.
  - For example, since you're adding API functionality (but not breaking anything) you might increase the minor version number.
  - Since this isn't the official release yet, add a prerelease suffix to your version
  - Gutcheck from another member of @mapbox/geocoding-gang 
- [x] Read over `CONTRIBUTING.md` which has instructions for triggering a binary build (https://github.com/mapbox/carmen-cache/blob/master/CONTRIBUTING.md)
- [ ] When ready, let's trigger a binary build with a commit

Next up: creating a branch in `carmen` and pointing at your new build

**Comment by miccolis** [comment]
Stale
