### ISSUE TITLE
Refactor followup: enable LTO

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carmen-cache#117]
After #116 lands, because #166 splits into multiple `.cpp` files, we should enable LTO for the build.

Learn more about LTO via https://github.com/mapbox/cpp/blob/lto-glossary-entry/glossary.md#link-time-optimization

/cc @aaaandrea @apendleton 

refs https://github.com/mapbox/cpp/pull/49

**Comment by apendleton** [comment]
@springmeyer it looks from cursory Googling like `lld` already supports LTO, so just to be sure I'm understanding: this should just be adding `-flto` to `cppflags` and `ldflags` in our binding.gyp, right?

**Comment by springmeyer** [comment]
@apendleton I'll get a working example going in node-cpp-skel next and then ping you when ready. Up to now I've used binutils-gold for linking and not lld and I'd like to give lld a shot.

**Comment by springmeyer** [comment]
> @apendleton I'll get a working example going in node-cpp-skel next

Here is a working example you can follow: https://github.com/mapbox/vtquery/pull/63

> Up to now I've used binutils-gold for linking and not lld and I'd like to give lld a shot.

Ideally need to do this https://github.com/mapbox/mason/issues/561 for easy lld usage, so I think sticking with binutils linker (per the vtquery example PR above) is ideal.

**Comment by apendleton** [comment]
@springmeyer we gave this a go and it seems not to be working, I think because we're trying to link to previously-built static libraries from Mason that were compiled with a different LLVM version (rocksdb, etc.). We get this error:

```
/home/travis/build/mapbox/carmen-cache/mason_packages/.link/bin/ld: error: LLVM gold plugin has failed to create LTO module: Invalid value (Producer: 'LLVM5.0.0git-30c4647' Reader: 'LLVM 3.9.1')
```

see for reference the job: https://travis-ci.org/mapbox/carmen-cache/jobs/346996737

Thoughts on how to proceed?

**Comment by springmeyer** [comment]
@apendleton yes, LTO requires a consistent major clang++ version to be used. That is my oversight: so due to the external dep we'll need to:

 - move to doing `mason build rocksdb` rather than `mason install rocksdb` to trigger source compiles
 - force the same compiler, which will require a slight tweak to mason to allow us to override the default (old) apple compilers at https://github.com/mapbox/mason/blob/6aa9591a336ac71bfa1974185b6ee784a9b6033a/mason.sh#L71-L72.

So, I recommend you continue the cleanup work without this LTO addition, to make sure you'r not blocked. We can hit it as a followup once the mason fix is available.

**Comment by springmeyer** [comment]
Mason fix is looking good at https://github.com/mapbox/carmen-cache/pull/119

**Comment by apendleton** [comment]
Done in https://github.com/mapbox/carmen-cache/pull/116
