### ISSUE TITLE
Drop dependency on libprotobuf

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carmen-cache#33]
We are already using [protozero](https://github.com/mapbox/protozero) for fast parsing of protobuf messages.

Now that `[protozero]` has a robust and well tested interface for writing (docs at https://github.com/mapbox/protozero/blob/master/tutorial.md#writing-protobuf-encoded-messages) we can drop the external dependency on `libprotobuf`, which is currently only used in `carmen::Cache::pack`.

TODO:

 - [ ] FIRST: upgrade protozero to version that includes writing support (https://github.com/mapbox/carmen-cache/issues/34)
 - [ ] remove building of libprotobuf code [here](https://github.com/mapbox/carmen-cache/blob/5840b1f7e781c6978d0b71b5a939ba2b6529b4db/binding.gyp#L4-L70)
 - [ ] remove references to libprotobuf dependency [here](https://github.com/mapbox/carmen-cache/blob/5840b1f7e781c6978d0b71b5a939ba2b6529b4db/binding.gyp#L91)
 - [ ] remove protoc generated header include: https://github.com/mapbox/carmen-cache/blob/5840b1f7e781c6978d0b71b5a939ba2b6529b4db/src/binding.hpp#L21
 - [ ] remove need to install libprotobuf via mason: https://github.com/mapbox/carmen-cache/blob/126f7d3b52c6e488159ea3a8707ab42e3e64060b/.travis.yml#L51-L58
 - [ ] port `carmen::Cache::pack` to use protozero writer (drop usage of `carmen::proto`): https://github.com/mapbox/carmen-cache/blob/master/src/binding.cpp#L196-L258

**Comment by yhahn** [comment]
:laughing:

**Comment by springmeyer** [comment]
This is done, tracking now over at #42
