### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carmen-cache#44]
@apendleton - I've merged https://github.com/mapbox/carmen-cache/pull/42 into master. So the next version of carmen cache should be lighter (less binaries to package) and a bit faster for writes (`carmen.pack`).

I'll let you decide when to release. There is no need to get #42 deployed soon, but it should be solid whenever something else triggers a release.

/cc @yhahn

**Comment by apendleton** [comment]
@springmeyer awesome, thanks. We have a broader carmen cleanup planned for this week during which I'll probably rip the dictcache code out of carmen-cache as we're not using it anymore, and will plan on rolling a new release after that.

**Comment by springmeyer** [comment]
@apendleton hey there - any movement on a new release? Just tagging you here to note that #45 would be great to land when you do release next.

**Comment by apendleton** [comment]
@springmeyer thanks for the nudge. I'm going to try and get this done tomorrow.

**Comment by springmeyer** [comment]
#45 landed, closing.
