### ISSUE TITLE
Codereview: While/break

### ISSUE THREAD

**Issue by joto** [mapbox/carmen-cache#46]
While looking at #45 I noticed two places with combinations of `while()` and `break`:
https://github.com/mapbox/carmen-cache/blob/master/src/binding.cpp#L110-L111
This can probably just be `while(item.next(1)) {`

and
https://github.com/mapbox/carmen-cache/blob/master/src/binding.cpp#L372-L375
Shouldn't that just be `if (item.next(1)) {`?

**Comment by springmeyer** [comment]
Thanks for the code review! Fixed in f9c2c13 in the branch that will land with #45
