### ISSUE TITLE
Crashing "real" test

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carmen-cache#7]
Tests are failing on linux and crashing on osx with https://github.com/mapbox/carmen-cache/commit/9b86b03d17852337fc7df54774b4f604c19a8fb3. One guess is memory corruption in `sortRelevReason` (https://github.com/mapbox/carmen-cache/blob/ce7b3bff02df04c7b699ff7929e199c7009b1613/src/binding.cpp#L1266-L1276). This guess is because I've only seen crashes inside a C++ sort function once before. Prof @kkaefer explains: https://github.com/mapnik/mapnik/issues/1087#issuecomment-4166377.

**Comment by yhahn** [comment]
@springmeyer travis seems happier with this change ^^ would love confirmation from a real OS X user when you have hte chance : )

https://travis-ci.org/mapbox/carmen-cache/builds/45757978

**Comment by springmeyer** [comment]
:+1: working great now on osx locally.
