### ISSUE TITLE
Update RocksDB: 4.13 -> 5

### ISSUE THREAD

**Issue by KaiBot3000** [mapbox/carmen-cache#96]
### Context:
We're running into some issues with `shard-carmen` that [may be caused by rocksdb](https://github.com/mapbox/shard-carmen/issues/20#issuecomment-296276543). I don't know where to start digging into this issue because I haven't worked with carmen-cache yet 🎉 

### Quest:
 Let's get on the most recent stable version as an introduction to how we use it in carmen-cache. 

capturing from chat:
![image](https://cloud.githubusercontent.com/assets/11284580/25634840/e631ea46-2f30-11e7-850f-99fbe3b85217.png)

cc'ing @aarthykc who may want to join in and @springmeyer who's agreed to spirit-guide.

**Comment by springmeyer** [comment]
The rough steps I'm seeing are:

  - Learn how to build, rebuild, and generally develop on carmen-cache. The main readme is very sparse, so we can improve it as we go. Started a branch to land improvements at #97 
  -  Create a new rocksdb package by:
    - Copying https://github.com/mapbox/mason/tree/master/scripts/rocksdb/4.13 to https://github.com/mapbox/mason/tree/master/scripts/rocksdb/5.3.3
    - Editing that 5.3.3. package to point at the latest release: https://github.com/facebook/rocksdb/releases
    - Set up [trigger](https://github.com/mapbox/mason#trigger) creds for mason and publish the new 5.3.3 package to a `rocksdb-5.3.3` mason branch
  - Branch `carmen-cache` and point at the `rocksdb-5.3.3` package on [this line](https://github.com/mapbox/carmen-cache/blob/425d914eaf95390756c91c28997cfd9fca384676/install_mason.sh#L10-L11) (note: this line will change in #95)
  - Ensure carmen-cache builds and tests pass
  - Publish a dev binary of carmen-cache
  - Test downstream 🎉

**Comment by apendleton** [comment]
Might be out of scope for this effort, but if it's possible to add the utility binaries to the mason build (particularly the `ldb` tool), that'd come in handy. I pretty often use it for debugging, and end up rebuilding locally, which is slooooow.....

**Comment by springmeyer** [comment]
Happy to add those as part of this push @apendleton. Thanks for mentioning it.

**Comment by miccolis** [comment]
Done in https://github.com/mapbox/carmen-cache/pull/136
